- include: centos5-setup.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version < '6'

- name: verify that X server exists
  stat: path=/usr/bin/X
  register: xsession

- name: verify that xterm session exists
  stat: path=/usr/bin/xterm
  register: xterm

- name: if X window system not installed warn us
  debug: msg="Could not find a GUI on this machine, Skipping VNC Install."
  when: not xsession.stat.exists or not xterm.stat.exists

- include: setup_vnc_ubuntu.yml
  when: ansible_distribution == "Ubuntu" and xsession.stat.exists and xterm.stat.exists

- include: setup_vnc_CentOS5.yml
  when: ansible_distribution == "CentOS" and {{ ansible_distribution_major_version | version_compare('6', '<') }} and xsession.stat.exists and xterm.stat.exists

- include: setup_vnc_CentOS.yml
  when: ansible_distribution == "CentOS" and {{ ansible_distribution_major_version | version_compare('6', '>=') }} and xsession.stat.exists and xterm.stat.exists
