- set_fact: ansible_python_interpreter=/usr/bin/python

- name: install xauth
  yum: name=xorg-x11-xauth state=present

- name: copy over the ubuntu vnc file
  copy: src=VNC-Server-5.2.3-Linux-x64.rpm dest=/tmp/VNC-Server-5.2.3-Linux-x64.rpm

- name: install the package
  yum: name=/tmp/VNC-Server-5.2.3-Linux-x64.rpm state=present disable_gpg_check=yes

- name: remove the rpm package
  file: path=/tmp/VNC-Server-5.2.3-Linux-x64.rpm state=absent

- name: copy over the /etc/pam.d/vncserver.custom 
  copy: src=vncserver.custom-cent dest=/etc/pam.d/vncserver.custom

- name: copy over the /etc/vnc/config.d/common.custom 
  copy: src=common.custom dest=/etc/vnc/config.d/common.custom

- name: copy over the /etc/vnc/config.custom 
  copy: src=config.custom dest=/etc/vnc/config.custom

- name: install the license
  shell: /usr/bin/vnclicense -add {{ VNCLICENSE }}

- name: remove old X11 locks
  file: path=/tmp/.X1-lock state=absent

- name: remove old X11 sockets
  file: path=/tmp/.X11-unix state=absent
  failed_when: False

- name: touch X11-unix
  file: path=/tmp/.X11-unix state=directory mode="a+rwxt"
  failed_when: False

- name: start vnc as atmo_user
  shell: /bin/su {{ ATMOUSERNAME }} -c /usr/bin/vncserver
  failed_when: False

- set_fact: ansible_python_interpreter=/usr/bin/python26
