---

XGUI:
  xsession_path: /usr/bin/xinit
  xterm_path: /usr/bin/Xorg
  vnc_dependencies:
    - xterm
    - git
  packages_to_remove:
    # - realvnc-vnc-server
    - gnome-screensaver
  packages:
    - xorg-x11-xauth
    # - tigervnc-server
    - novnc

# VNC_COMMANDS:
#   - "/usr/bin/pkill gnome-screensaver"
#   - /bin/su {{ ATMOUSERNAME }} -c "/usr/bin/printf '%s\n%s\n' 'display' 'display' | vncpasswd /home/{{ ATMOUSERNAME }}/.vnc/passwd"
#   - "/usr/bin/pkill websockify"
#   - /usr/bin/vnclicense -add {{ VNCLICENSE }}
#   - /bin/su {{ ATMOUSERNAME }} -c /usr/bin/vncserver :1
#   - "for i in $(/usr/bin/pgrep -f '/opt/kanaka-noVNC-8b0a0f6/utils/');do /bin/echo 'killing process:' $i; /bin/kill -HUP $i;done"
#   - "/bin/su {{ ATMOUSERNAME }} -c '/usr/bin/vncserver -localhost :2 -SecurityTypes=VNCAuth,TLSVnc'"
#   - "websockify -D --web /usr/share/novnc/ 4200 localhost:5902 &"

# VNC_COMMANDS:
#   - "/usr/bin/pkill gnome-screensaver"
#   - /bin/su {{ ATMOUSERNAME }} -c "/usr/bin/printf '%s\n%s\n' 'display' 'display' | vncpasswd -file /home/{{ ATMOUSERNAME }}/.vnc/passwd"
#   - "/usr/bin/pkill websockify"
#   - /usr/bin/vnclicense -add {{ VNCLICENSE }}
#   - /bin/su {{ ATMOUSERNAME }} -c /usr/bin/vncserver :1
#   - "for i in $(/usr/bin/pgrep -f '/opt/kanaka-noVNC-8b0a0f6/utils/');do /bin/echo 'killing process:' $i; /bin/kill -HUP $i;done"
#   - "/bin/su {{ ATMOUSERNAME }} -c '/usr/bin/vncserver -localhost :2 -SecurityTypes=VNCAuth,TLSVnc'"
#   # To disable NoVNC web when entering prod, remove "--web /usr/share/novnc/" from the command below
#   - "websockify -D --web /usr/share/novnc/ 6080 localhost:5902 &"
