---

SSHD: sshd

PACKAGES:
  - epel-release
  - python26
  - zsh
  - tmux
  - screen
  - autoconf
  - gcc
  - make
  - tcsh
  - nss_ldap
  - patch
  - fuse
  - fuse-devel.x86_64
  - python
  - python-ldap
