---

SSHD: ssh

PACKAGES:
  - libfam0
  - python
  - python-ldap
  - python-software-properties
  - python-httplib2
  - libfuse2
  - tmux
  - screen
  - autoconf
  - gcc
  - make
  - patch
  - tcsh
  - zsh
  - mosh
  - fuse-utils
  - fuse
