---
# Requires ATMOUSERNAME and VNCLICENSE
- name: Playbook lists roles that should be executed after ATMOUSERNAME has been created
  hosts: atmosphere
  roles:
    - atmo-fail2ban
    - irods-icommands  #TODO: jetstream --skip-tags icommands-setup
    - atmo-realvncserver  #TODO: jetstream --skip-tags vnc
    - atmo-cleanup
