---
- name: Playbook to add globus connect to the instance
  hosts: atmosphere
  roles:
      # GLOBUS_ENDPOINT variable required 
      # TODO: don't uncomment without tagging the role 'globus-connect'
      # TODO: Cyverse: skip-tags 'globus-connect'
      # - atmo-globus-connect
