---

- name: It is now possible to gather facts
  setup:

- name: Gather OS-specific variables
  include_vars: "{{ item.var }}"
  when: "{{ item.condition }}"
  with_items:
    - { var: 'Ubuntu.yml', condition: ansible_distribution == "Ubuntu" }
    - { var: 'CentOS.yml', condition: ansible_distribution == "CentOS" }
  tags: vars

- name: Make sure ssh directory exists with correct permissions
  file:
    path: /root/.ssh/
    state: directory
    mode: "0700"

- name: Make changes to /etc/ssh/sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    backup: true
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ SSHD_CHANGES }}"
    - { regexp: "{{ PORT_ENTRY_REGEXP }}", line: "{{ PORT_ENTRY_LINE }}", state: 'present' }
    - { regexp: "", line: "AllowGroups {{ SSH_ALLOW_GROUPS }}", state: 'present' }
  tags: sshd-config

- name: Restart SSH service
  service:
    name: "{{ SSH_SERVICE }}"
    state: restarted
