- name: restart apache
  service: name=apache state=restarted

- name: restart centos ssh
  service: name=sshd state=restarted

- name: restart ubuntu ssh
  service: name=ssh state=restarted

- name: update ubuntu timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
