- name: bootscript_1 - make directories for post scripts and logs
  file: path={{ item }} state=directory
  with_items: '{{ POST_MAKE_DIR }}'

- name: bootscript_2 - touch log files
  file: path={{ item }} state=touch
  with_items: '{{ POST_SCRIPT_LOGS }}'

- name: bootscript_3 - run user's scripts in script directory
  shell: >
    for SCRIPT in {{ POST_SCRIPT_DIR_RUN }};
    do
        if [ -f $SCRIPT -a -x $SCRIPT ]
        then
            $SCRIPT 2>> {{ POST_SCRIPT_LOG_STDERR }} >> {{ POST_SCRIPT_LOG_STDOUT }}
        fi
    done
