---
# ansible-playbook playbooks/utils/unmount_volume.yml -i hosts --limit "vm0" -e "{ 'src':'/dev/vdc' }"


- set_fact: ansible_python_interpreter=/usr/bin/python2.6
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version < '5')

- name: register mountpoint and fstype
  shell: grep "^{{ src }} " /proc/mounts | cut -d ' ' -f 2,3 | awk '{ printf "[\"%s\",\"%s\"]\n", $1, $2 }' 
  register: result

- name: Print out mountpoints for the device {{ src }}
  debug: msg="{{ (item |from_json )[0] }} {{ src }} {{ (item |from_json )[1] }}" 
  with_items:
    - "{{ result.stdout_lines }}"

- name: Loop through list and unmount
  mount: name="{{ (item |from_json )[0] }}" src="{{ src }}" fstype="{{ (item |from_json )[1] }}" state=unmounted
  with_items:
    - "{{ result.stdout_lines }}"
