- name: Add users ssh keys to authorized_keys2
  authorized_key: user=root key='{{ USERSSHKEYS|join("\n") }}' state=present exclusive=yes path=/root/.ssh/authorized_keys2
  become: yes
  when: USERSSHKEYS is defined

- name: Add users ssh keys to authorized_keys to home directory of user
  authorized_key: user={{ ATMOUSERNAME }} key='{{ USERSSHKEYS|join("\n") }}' state=present exclusive=yes
  when: USERSSHKEYS is defined

- name: grab local copy of user ssh private key
  set_fact: pk_file="{{ lookup('file', '/tmp/' + ATMOUSERNAME + '_default.pub') }}"
  tags: debug

- name: distribute the generated gate one key to the instance
  authorized_key: >
    key='{{ pk_file }}'
    state=present
    user="{{ item }}"
  with_items:
    - root
    - "{{ ATMOUSERNAME }}"
  ignore_errors: yes
  tags:
    - ssh-keys
    - debug

- name: remove user key from controller node
  local_action: file path=/tmp/{{ ATMOUSERNAME }}_default.pub state=absent
  tags:
    - ssh-keys
    - delete-key
