- name: Add users ssh keys to authorized_keys2
  authorized_key: user=root key='{{ USERSSHKEYS|join("\n") }}' state=present exclusive=yes path=/root/.ssh/authorized_keys2
  become: yes
  when: USERSSHKEYS is defined
