- name: Add users ssh keys to authorized_keys2
  authorized_key: user=root key='{{ USERSSHKEYS|join("\n") }}' state=present exclusive=yes path=/root/.ssh/authorized_keys2
  become: yes
  when: USERSSHKEYS is defined

- name: Add users ssh keys to authorized_keys to home directory of user
  authorized_key: user={{ ATMOUSERNAME }} key='{{ USERSSHKEYS|join("\n") }}' state=present exclusive=yes path=/home/{{ ATMOUSERNAME }}/.ssh/authorized_keys
  when: USERSSHKEYS is defined

- name: build ssh private key path
  set_fact: pk_path="/tmp/{{ ATMOUSERNAME }}_default.pub"

- name: distribute the generated gate one key to the instance
  authorized_key: >
    key="{{ lookup('file', '{{ pk_path }}') }}"
    state=present
    user=root
  ignore_errors: yes
  tags:
    - ssh-keys

- name: remove user key from controller node
  local_action: file path=/tmp/{{ ATMOUSERNAME }}_default.pub state=absent
  tags:
    - ssh-keys