--- 
# TODO NOTE: when moving to ansible 2.0 we should use ansible_host, ansible_port, and ansible_user
- name: verify that host is reachable via ssh port
  local_action: wait_for port={{ SSH_PORT }} host="{{ ansible_ssh_host | default(inventory_hostname) }}" search_regex=OpenSSH timeout={{ SSH_TIMEOUT }} 
  tags: verify-ssh

- name: test default ansible connection
  local_action: "shell ssh -p {{ ansible_ssh_port }} root@{{ ansible_ssh_host }} 'echo hello world test' | grep 'hello world test'"
  register: default_remote_user
  ignore_errors: yes

###
# CENTOS SETUP
###
- name: test centos connection
  local_action: "shell ssh -p {{ ansible_ssh_port }} centos@{{ ansible_ssh_host }} 'echo hello'"
  register: centos_remote_user
  ignore_errors: yes
  when: default_remote_user|failed

###
# UBUNTU SETUP
###
- name: test ubuntu connection
  local_action: "shell ssh -p {{ ansible_ssh_port }} ubuntu@{{ ansible_ssh_host }} 'echo hello'"
  register: ubuntu_remote_user
  ignore_errors: yes
  when: default_remote_user|failed and centos_remote_user|failed

#- debug: var=default_remote_user
#- debug: var=centos_remote_user
#- debug: var=ubuntu_remote_user

- name: fail when ssh not possible
  fail: msg="The host is not reachable via SSH as root and cloud users."
  when: (default_remote_user.stdout is defined and default_remote_user.stdout != "hello world test") or 
        (centos_remote_user.stdout is defined and centos_remote_user.stdout != "hello world test") or 
        (ubuntu_remote_user.stdout is defined and ubuntu_remote_user.stdout != "hello world test")

