---
# tasks to install irods
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"
  tags:
    - vars
    - icommands-setup

- name: Install FUSE dependencies for CentOS
  yum: name={{ item }}
  with_items:
    - fuse
    - fuse-libs
  when: (ansible_distribution == "CentOS")
  tags: icommands-setup

- name: Download iCommands archive for CentOS 5
  get_url:
    url: "{{ ICOMMANDS_URL }}"
    dest: /tmp/{{ ICOMMANDS_TAR }}
    validate_certs: false
  changed_when: false
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version < '6')
  tags: icommands-setup

- name: Extract iCommands for CentOS 5
  command: "tar -xvf /tmp/{{ ICOMMANDS_TAR }} -C {{ ICOMMANDS_DESTINATION }}"
  changed_when: false
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version < '6'
  tags: icommands-setup

- name: Download iRODS FS for CentOS 5
  get_url:
    url: "{{ IRODSFS_URL }}"
    dest: "{{ IRODSFS_DESTINATION }}"
    validate_certs: false
    mode: a+x
  changed_when: false
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version < '6')
  tags: icommands-setup

- name: add icommands to path for centos 5
  lineinfile: dest=/home/{{ ATMOUSERNAME }}/.bashrc line='export PATH=$PATH:/opt/icommands'
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version < '6'
  tags: icommands-setup

- name: delete irods and icommand executables for non-CentOS 5
  file: path={{ item }} state=absent
  with_items:
    - "{{ IRODSFS_DESTINATION }}"
    - "{{ IRODSFS_LINK }}"
    - "{{ ICOMMANDS_DESTINATION }}/icommands"
  when: not (ansible_distribution == "CentOS" and ansible_distribution_major_version < '6')
  tags: icommands-setup

- name: delete any dead soft links in /usr/local/bin
  command: find -L {{ BIN_PATH }} -type l -delete
  changed_when: false
  when: not (ansible_distribution == "CentOS" and ansible_distribution_major_version < '6')
  tags: icommands-setup

- name: remove archaic icommands path from user's bashrc
  lineinfile: dest=/home/{{ ATMOUSERNAME }}/.bashrc line='export PATH=$PATH:/opt/icommands' state=absent
  when: not (ansible_distribution == "CentOS" and ansible_distribution_major_version < '6')
  tags: icommands-setup

- name: Download installation package for non-CentOS 5
  get_url:
    url: "{{ ICOMMANDS_URL }}"
    dest: /tmp/icommands-pkg.rpm
  changed_when: false
  when: not (ansible_distribution == "CentOS" and ansible_distribution_major_version < '6')
  tags: icommands-setup

- name: Install iCommands for Ubuntu
  apt:
    deb: /tmp/icommands-pkg.rpm
  when: ansible_distribution == "Ubuntu"
  tags: icommands-setup

- name: Install iCommands for CentOS 6 and 7
  yum:
    name: /tmp/icommands-pkg.rpm
    state: present
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version > "5")
  tags: icommands-setup
