---
# tasks to install irods
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"
  tags:
    - vars
    - icommands-setup

- name: copy over irods executables for centos 5
  copy: src={{ IRODS_EXECUTABLE }} dest={{ IRODS_DESTINATION }} mode=a+x
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version < '6')
  tags: icommands-setup

- name: copy over icommands for centos 5
  unarchive: src={{ ICOMMANDS_TAR }} dest={{ ICOMMANDS_DESTINATION }} copy=yes creates=yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version < '6'
  tags: icommands-setup

- name: add icommands to path for centos 5
  lineinfile: dest=/home/{{ ATMOUSERNAME }}/.bashrc line='export PATH=$PATH:/opt/icommands'
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version < '6'
  tags: icommands-setup

- name: delete irods and icommand executables for other os'es
  file: path={{ item }} state=absent
  with_items:
    - "{{ IRODS_DESTINATION }}"
    - "{{ IRODS_LINK }}"
    - "{{ ICOMMANDS_DESTINATION }}/icommands"
  when: not (ansible_distribution == "CentOS" and ansible_distribution_major_version < '6')
  tags: icommands-setup

- name: delete any dead soft links in /usr/local/bin
  command: find -L {{ BIN_PATH }} -type l -delete
  when: not (ansible_distribution == "CentOS" and ansible_distribution_major_version < '6')
  tags: icommands-setup

- name: remove archaic icommands path from user's bashrc
  lineinfile: dest=/home/{{ ATMOUSERNAME }}/.bashrc line='export PATH=$PATH:/opt/icommands' state=absent
  when: not (ansible_distribution == "CentOS" and ansible_distribution_major_version < '6')
  tags: icommands-setup

- name: Copy installation package for Ubuntu
  # We use Ubuntu 14.04 installation package for Ubuntu 16.04
  copy: src=irods-icommands-4.1.9-ubuntu{{ [ansible_distribution_major_version, 14] | min }}-x86_64.deb dest=/tmp/
  when: ansible_distribution == "Ubuntu"
  tags: icommands-setup

- name: Copy installation package for CentOS 6 and 7
  copy: src=irods-icommands-4.1.9-centos{{ ansible_distribution_major_version }}-x86_64.rpm dest=/tmp/
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version > "5")
  tags: icommands-setup

- name: Install FUSE dependencies for CentOS 6 and 7
  yum: name={{ item }}
  with_items:
    - fuse
    - fuse-libs
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version > "5")
  tags: icommands-setup

- name: Install iCommands for Ubuntu
  apt:
    deb: /tmp/irods-icommands-4.1.9-ubuntu{{ [ansible_distribution_major_version, 14] | min }}-x86_64.deb
  when: ansible_distribution == "Ubuntu"
  tags: icommands-setup

- name: Install iCommands for CentOS 6 and 7
  yum:
    name: /tmp/irods-icommands-4.1.9-centos{{ ansible_distribution_major_version }}-x86_64.rpm
    state: present
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version > "5")
  tags: icommands-setup
