# tasks to install irods
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"
  tags: vars

- name: copy over irods executables for centos 5
  copy: src={{ IRODS_EXECUTABLE }} dest={{ IRODS_DESTINATION }} mode=a+x
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version < '6')

- name: copy over icommands for centos 5
  unarchive: src={{ ICOMMANDS_TAR }} dest={{ ICOMMANDS_DESTINATION }} copy=yes creates=yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version < '6'

- name: add icommands to path for centos 5
  lineinfile: dest=/home/{{ ATMOUSERNAME }}/.bashrc line='export PATH=$PATH:/opt/icommands'
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version < '6'

- name: delete irods and icommand executables for other os'es
  file: path={{ item }} state=absent
  with_items:
    - "{{ IRODS_DESTINATION }}"
    - "{{ IRODS_LINK }}"
    - "{{ ICOMMANDS_DESTINATION }}/icommands"
  when: not (ansible_distribution == "CentOS" and ansible_distribution_major_version < '6')

- name: remove archaic icommands path from user's bashrc
  lineinfile: dest=/home/{{ ATMOUSERNAME }}/.bashrc line='export PATH=$PATH:/opt/icommands' state=absent
  when: not (ansible_distribution == "CentOS" and ansible_distribution_major_version < '6')
