---

- name: Copy installation package for Ubuntu
  # We use Ubuntu 14.04 installation package for Ubuntu 16.04
  copy: src=irods-icommands-4.1.9-ubuntu{{ [ansible_distribution_major_version, 14] | min }}-x86_64.deb dest=/tmp/
  when: ansible_distribution == "Ubuntu"
  tags: icommands-setup

- name: Copy installation package for CentOS 6 and 7
  copy: src=irods-icommands-4.1.9-centos{{ ansible_distribution_major_version }}-x86_64.rpm dest=/tmp/
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version > "5")
  tags: icommands-setup

- name: Install FUSE dependencies for CentOS 6 and 7
  yum: name={{ item }}
  with_items:
    - fuse
    - fuse-libs
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version > "5")
  tags: icommands-setup

- name: Install iCommands for Ubuntu
  apt:
    deb: /tmp/irods-icommands-4.1.9-ubuntu{{ [ansible_distribution_major_version, 14] | min }}-x86_64.deb
  when: ansible_distribution == "Ubuntu"
  tags: icommands-setup

- name: Install iCommands for CentOS 6 and 7
  yum:
    name: /tmp/irods-icommands-4.1.9-centos{{ ansible_distribution_major_version }}-x86_64.rpm
    state: present
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version > "5")
  tags: icommands-setup
