---
- name: this is the playbook for adding an ssh key to a gateone user
  hosts: gateone-hosts

  tasks:
    - name: ensure the existence of the user directory
      local_action: file path="/var/lib/gateone/users/{{ ATMOUSERNAME }}/.ssh" owner=root group=root mode=0700 state=directory
      delegate_to: "{{groups['gateone-hosts'][0]}}"

    - name: check the existence of a given ssh key by name
      local_action: stat path="/var/lib/gateone/users/{{ ATMOUSERNAME }}/.ssh/{{ ATMOUSERNAME }}_default"
      register: go_key
      delegate_to: "{{groups['gateone-hosts][0]'}}"
    
    - name: generate the public key
      local_action: command "/usr/bin/ssh-keygen -N '' -t rsa -b 2048 -f /var/lib/gateone/users/{{ ATMOUSERNAME }}/.ssh/{{ ATMOUSERNAME }}_default -C {{ ATMOUSERNAME }}"
      when: go_key.stat.exists == False
      delegate_to: "{{groups['gateone-hosts'][0]}}"
    
    - name: set the permissions on the private key file
      local_action: file path="/var/lib/gateone/users/{{ ATMOUSERNAME }}/.ssh/{{ ATMOUSERNAME }}_default" mode=0644
      delegate_to: "{{groups['gateone-hosts'][0]}}"
    
    - name: add the key name to .default_ids
      local_action: lineinfile dest="/var/lib/gateone/users/{{ ATMOUSERNAME }}/.ssh/.default_ids" line="{{ ATMOUSERNAME }}_default" create=yes state=present
      delegate_to: "{{groups['gateone-hosts'][0]}}"

    - name: finally, transfer the public key locally
      local_action: fetch src="/var/lib/gateone/users/{{ ATMOUSERNAME }}/.ssh/{{ ATMOUSERNAME }}_default.pub" dest="{{ GATEONE_LOCAL_PUBKEY_DIR | default('/tmp/') }}" flat=yes
  roles:
    #- gateone-gen-sshkey
