LDAP_PACKAGES:
  packages:
    - pam
    - openldap
    - openssl
    - openssl-devel
    - pam_mkhomedir.so
    - pam_ldap.so
  state: present

LDAP_CONF_PATH: /etc/ldap.conf

SSSD_CONF_PATH: /etc/sssd/sssd.conf

LDAP_AUTHCONFIG: authconfig --enableldap --enableldapauth --ldapserver=ldap.iplantc.org --ldapbasedn="ou=People,dc=iplantcollaborative,dc=org" --enablelocauthorize --update

LDAP_SERVICE: nscd

TEST_LDAP_USER: mattd-test01
